### ISSUE TITLE
Scroll direction on the scrollbar is opposite in Edit menu. (From Alisa.)

### ISSUE THREAD

**Issue by ctrlaltdavid** [highfidelity/hifi#10038]
Scrollbar problems happen in the tablet in (at least) the following dialogs:
- Entities list.
- Entity properties.
- "All markets" marketplace page.
- Clara.io marketplace page.

Each seems to have different combinations of problems happening in desktop (with mouse) versus HMD (with finger).

**Comment by AlanZimmerman** [comment]
Also, this may be a separate bug but I've noticed that the scrollbar in edit>properties has an issue where, once clicked, it keeps focus and sticks to the cursor even when clicking elsewhere. It becomes impossible to scroll down to a section and stay there.

**Comment by ctrlaltdavid** [comment]
PR: https://github.com/highfidelity/hifi/pull/10065

This PR also fixes the edit>properties scrollbar sticking to the cursor, I believe.
