### ISSUE TITLE
Cannot light fuse in tutorial-external build 6136

### ISSUE THREAD

**Issue by sharsein** [highfidelity/hifi#10047]
Desktop PC - Windows 10 Home - CPU 3.5GHz Intel i5-6600K - GTX1060 - RAM 16GB - Tested with HTC Vive
Tested: Windows: http://highfidelity.com/download/win/6136

When I put my controller in the purple sphere and pull the trigger, lighter goes flying
![equipfail1](https://cloud.githubusercontent.com/assets/3520695/24433959/4b13ab2c-13e1-11e7-8512-4fcc4d63832b.gif)
![equipfail2](https://cloud.githubusercontent.com/assets/3520695/24433960/4b14271e-13e1-11e7-8fe5-65ab926fffdf.gif)
[lighterequipissuesfullvid.zip](https://github.com/highfidelity/hifi/files/877475/lighterequipissuesfullvid.zip)

Notes:

- Pulled on 3/27 and tried making a build. I can equip and light the lighter, but the fuse does not light. Will file separate issue after I confirm I made the build properly. 
- Issue also experienced by Steam reviewer elk197 on 3/19

**Comment by sharsein** [comment]
After playing with build 6227, I am only able to reproduce this bug when I have Third Person view enabled with VR. I'm guessing that's what the issue actually is. Although the game does switch to First Person view when VR mode is enabled, it might be a good idea to disable the option to switch to Third Person view unless in desktop mode.

**Comment by AndrewMeadows** [comment]
Closing this: we no longer use this tutorial.
