### ISSUE TITLE
tablet page doesn't emit web events if script(s) reloaded

### ISSUE THREAD

**Issue by KevinFrutiger** [highfidelity/hifi#10055]
If I reload a tablet app script, the page it loads with gotoWebScreen() breaks. It doesn't fire any webEventReceived handlers in the main app script.

Test app:
https://kevinfrutiger.github.io/hifi-tablet-bug-march29/launchAvatarApp.js
(Avatar 2 is the same as Avatar 1, but with glasses)

Steps to reproduce:
1. Load tablet app script
2. Tablet app functions as expected (the avatar buttons change the avatar)
3. Reload script from the Running Scripts... dialog, or Edit > Reload all scripts
(doesn't matter if you close the tablet first or not)
4.  App button works, but page loaded by gotoWebScreen() -- i.e. the UI -- no longer fires any of the webEventReceived handlers in the main app script (avatar doesn't change, print statements don't fire)

To resolve, I have to relaunch Interface any time I make changes to the main app logic.

Windows 10 desktop client (in 2D mode)
build 6223

**Comment by hyperlogic** [comment]
Closing, now that this PR has landed in master.  Please reopen this issue, if there is still a problem.
