### ISSUE TITLE
When you connect to a domain that is not responding a popup comes up. Move it to the tablet (see details)

### ISSUE THREAD

**Issue by cozza13** [highfidelity/hifi#10054]
Repro. 

-Launch Interface
-go to the following location hifi://123.123.123.123
-You will see a popup that shows up 
![capture](https://cloud.githubusercontent.com/assets/464312/24459940/a733f234-1451-11e7-9418-a75d84b0d60a.PNG)
Move this to the tablet

**Comment by vladest** [comment]
starting on this

**Comment by vladest** [comment]
PR: https://github.com/highfidelity/hifi/pull/10066
