### ISSUE TITLE
Cannot light fuse--3/28 internal

### ISSUE THREAD

**Issue by sharsein** [highfidelity/hifi#10050]
Desktop PC - Windows 10 Home - CPU 3.5GHz Intel i5-6600K - GTX1060 - RAM 16GB - Tested with HTC Vive
Tested: Pull from master Release-6222 069ebaedf0

I can equip and light the lighter, but fuse does not catch fire.
![nofire](https://cloud.githubusercontent.com/assets/3520695/24440716/8ab30f6a-140a-11e7-8c3b-369edf7adcd2.gif)

**Comment by AndrewMeadows** [comment]
Closing this: we no longer use this tutorial.
