### ISSUE TITLE
Selecting a particle effect doesn't enable the particle effect menu. (From Alisa.)

### ISSUE THREAD

**Issue by cozza13** [highfidelity/hifi#10060]
I believe what is happening is that the pop down in particles is not popping down.

**Comment by ctrlaltdavid** [comment]
You need to click on the "Open Controls" text in order to show the particle edit fields.

**Comment by ctrlaltdavid** [comment]
This is just not being able to select an emitter by clicking on it, which is logged as a problem elsewhere I believe.

**Comment by SamGondelman** [comment]
this was resolved and also is outdated with the new edit layout
