### ISSUE TITLE
When using Goto and moving between areas, you can get in a situation where the place you go to stays in your goto filter. The result is that you can not see other locations

### ISSUE THREAD

**Issue by cozza13** [highfidelity/hifi#10099]
![pasted image at 2017_03_31 03_30 pm](https://cloud.githubusercontent.com/assets/464312/24580624/e29742d4-16bf-11e7-9303-ebe39f4fe9e1.png)

**Comment by vladest** [comment]
starting on this

**Comment by vladest** [comment]
I can see 2 issues here:
- address input not cleared on location change
- address bar not editable, so, basically not possible to change filter

is this correct?

**Comment by sethalves** [comment]
Yes (though the address bar is editable before changing domains).

**Comment by vladest** [comment]
try PR: https://github.com/highfidelity/hifi/pull/10102

**Comment by SamGondelman** [comment]
PR was merged a while ago
