### ISSUE TITLE
GoTo: Filtering by name does not work properly

### ISSUE THREAD

**Issue by anshuman64** [highfidelity/hifi#10114]
Repro:
1) Open tablet > Go To
2) Type in "me" in search bar
Mexico should be #1 result, but other locations without those letters show up

**Comment by vladest** [comment]
picking this one

**Comment by howard-stearns** [comment]
Wait!

@anshuman64 can you tell me more about what is showing up and why you think it shouldn't?
I want to distinguish between a bug, where things are not working as designed, vs a project with a newly articulated goal.

Please see the description of search, near the end of https://blog.highfidelity.com/blog/2016/11/20/content-discovery-part-2-how (And see also the link to part 1.)

**Comment by anshuman64** [comment]
Just read through that blog post... Thank you for sending it over Howard! It's pretty cool what your guys' vision for Discovery.
I think since there are few domains in existence, I was expecting simple autocomplete. I only know of a few domains, so when typing "Me..." in Places, I expected Mexico to pop up as the first result. However, it was the 7th result for me.
Therefore, I understand that it must be working properly and I'm excited to see its performance with a large number of domains. The couple suggestions I could make: 
1) It was only recently that I realized Discovery = GoTo. GoTo seems like an inappropriate name since you can also use it to search for snaps. Maybe Search?
2) Introduce heavier weighting for the first letters typed. Just because "Me" is at the end of WelcoME, I probably did not intend to go to Welcome (despite there being 7 people there).
Either way, closing this issue for now.
