### ISSUE TITLE
hmd keyboard doesn't appear for facebook username textfield

### ISSUE THREAD

**Issue by sethalves** [highfidelity/hifi#10134]
either press ctrl-b or get there fix the like-button in the goto page.  notice that clicking on the password field brings up the keyboard, but clicking on the username field doesn't.

**Comment by ctrlaltdavid** [comment]
Seth's asked me to have a look at this one.

**Comment by ctrlaltdavid** [comment]
PR: https://github.com/highfidelity/hifi/pull/10331

**Comment by SamGondelman** [comment]
PR was merged a while ago
