### ISSUE TITLE
In Tablet desktop you can get the error "desktop not defined"

### ISSUE THREAD

**Issue by cozza13** [highfidelity/hifi#10139]
Open tablet in desktop mode. 

- Click People. 
- click on a person and go to their profile page. 
- click the tweet button.

![capture](https://cloud.githubusercontent.com/assets/464312/24738621/b6f67cd2-1a4b-11e7-8fac-80e955ff0a93.PNG)

**Comment by vladest** [comment]
picking up this one

**Comment by vladest** [comment]
Cant got to profile. Is this master branch?

**Comment by SamGondelman** [comment]
This works for me in stable now
