### ISSUE TITLE
Hover on the forward and back buttons and home button turns white.

### ISSUE THREAD

**Issue by cozza13** [highfidelity/hifi#10140]
Open tablet 
- open Go to
- hover mouse of forward and back and home. 
- They turn white. Change them to default hover color. 

![capture](https://cloud.githubusercontent.com/assets/464312/24738658/fa296a96-1a4b-11e7-9807-1a05daae76b4.PNG)

**Comment by vladest** [comment]
Starting on this

**Comment by vladest** [comment]
PR: https://github.com/highfidelity/hifi/pull/10162

**Comment by SamGondelman** [comment]
PR was merged a while ago
