### ISSUE TITLE
When you press ctrl+s you hear a noise. If you click from tablet there is no sound

### ISSUE THREAD

**Issue by cozza13** [highfidelity/hifi#10164]
When this is complete this Fogbugz should be signed off. https://highfidelity.fogbugz.com/f/cases/4010/Snapshots-Snaps-button-Click-Snap-button-sound-not-working

**Comment by vladest** [comment]
picking this one

**Comment by vladest** [comment]
task: add same shutter sound to Tablet's snapshot

**Comment by vladest** [comment]
PR: https://github.com/highfidelity/hifi/pull/10194
