### ISSUE TITLE
Login button presented after snapshot. "Cancel" not working

### ISSUE THREAD

**Issue by cozza13** [highfidelity/hifi#10165]
Snapshots: Snaps Button: Cancel 'Get Login Prompt' not working

- Logout
- Go to "welcome"
- Take a snapshot
- Click share button (login comes up)
- click cancel

cancel will not work

once complete close the ticket here https://highfidelity.fogbugz.com/f/cases/4007/Snapshots-Snaps-Button-Cancel-Get-Login-Prompt-not-working

**Comment by vladest** [comment]
picking up this one

**Comment by vladest** [comment]
PR: https://github.com/highfidelity/hifi/pull/10174
