### ISSUE TITLE
Add a hover capability on Snaps and Places. Similar to what happens when you bring up goto with the "enter" key

### ISSUE THREAD

**Issue by cozza13** [highfidelity/hifi#10166]
Make the hover be an underline. 

![capture](https://cloud.githubusercontent.com/assets/464312/24817075/f3d22e7c-1b8f-11e7-9291-fa543fb6c573.PNG)

close this when done https://highfidelity.fogbugz.com/f/cases/edit/3988/Hovering-over-the-title-bar-with-mouse-does-not-produce-expected-results

**Comment by vladest** [comment]
picking up this one

**Comment by vladest** [comment]
PR: https://github.com/highfidelity/hifi/pull/10176
Chris, hope I understood this correctly (underline on hover)
