### ISSUE TITLE
Record Script Blendshapes only play back once.

### ISSUE THREAD

**Issue by Menithal** [highfidelity/hifi#10404]
The Record Script avatar Blend-shapes seem to playback once, after which the the blendshapes never get updated

**Comment by ctrlaltdavid** [comment]
@Menithal The mouth shapes play back the first loop through the recording but then not through subsequent loops? (I'm surprised they get played back even the first time through.)

**Comment by Menithal** [comment]
Yes. That seems to happen. Or atleast for. Few moments. I need to test it a bit more, but that's what seems to happen

**Comment by ctrlaltdavid** [comment]
PR: https://github.com/highfidelity/hifi/pull/10433

**Comment by ctrlaltdavid** [comment]
Updated PR: https://github.com/highfidelity/hifi/pull/10443
Merged into build 6499.
