### ISSUE TITLE
Interface does not always close properly

### ISSUE THREAD

**Issue by sharsein** [highfidelity/hifi#10400]
Desktop PC - Windows 10 Home - CPU 3.5GHz Intel i5-6600K - GTX1060 - RAM 16GB - Tested with HTC Vive.
I tested build 6460. Bug was originally found by kevinmthomas on build 6457. 

I clicked the x on HiFI interface, then tried to relaunch using the desktop shortcut. Checked task manager when nothing happened and it turns out it is actually running in the background. If force quit with task manager it restarts fine, and then closing it will completely close, so also not a consistent repro.

![interfacerrunningbutnot](https://cloud.githubusercontent.com/assets/3520695/25775368/50e33ece-3258-11e7-91c8-4889f3ab180e.PNG)

Log: 
[hifi-log.txt](https://github.com/highfidelity/hifi/files/981133/hifi-log.txt)

**Comment by themelissabrown** [comment]
Might be related to this PR https://github.com/highfidelity/hifi/pull/10358

**Comment by SamGondelman** [comment]
This is a pretty broad and old issue.  We've fixed lots of shutdown problem in the past 2 years (and ~900 builds), and QA hasn't reported any shutdown issues in a while.  I'm going to close this, but we can re-open it if new shutdown problems appear.
