### ISSUE TITLE
Overlays parented to other Model Overlays don't currently track joint positions or rotations.

### ISSUE THREAD

**Issue by humbletim** [highfidelity/hifi#10809]
Here's a test script and example output to demonstrate the problem:
[test-parented-overlay-children.js](https://gist.githubusercontent.com/humbletim/516f445eba8cbe17d7eaa8b2ac135466/raw/c3643e82a576e5674535051c1192e99e3af20605/test-parented-overlay-children.js)

![image](http://imgur.com/nTaR9Vz.gif)
* On the top is a _Model Entity_ with a child overlay that correctly tracks its LeftHand joint.
* On the bottom is a _Model Overlay_ with a child overlay that should be tracking the LeftHand joint, but doesn't.

**Comment by sbennett77** [comment]
Currently Testing.
