### ISSUE TITLE
HiFi solution AutoMoc error

### ISSUE THREAD

**Issue by Armads** [highfidelity/hifi#10828]
(Apologies in advance if this isn't the proper place to ask this sort of question; but any input I can get would be appreciated.)

I've been getting a weird error trying to build the HiFi solution... not a whole lot of information to go on which is why it's been hard trying to track down.

`error: "(solutionDir)/hifi/tests/entities/src/main.cpp" File: AutoMoc`
`error: "(solutionDir)/hifi/tests/render-perf/src/main.cpp" File: AutoMoc`

No line numbers for the errors are given and double-clicking to try to go to the source file does nothing. But I have verified that the files it's complaining about do exist--and that they both attempt to include a file named `"main.moc"`.

I'm using Visual Studio 2013 Community (with update 5) on Windows 10 x64. I followed the build directions at https://wiki.highfidelity.com/wiki/Build_Guide_for_Windows_64-bit, and I also had to set an environment variable for the VS2013 install directory (which caused more errors and warnings if it was not set) but these two errors are persistent.

My best guess is that these have something to do with CMake but I can't discern inough info to tell for sure what's going on or why it's failing. Has anyone else seen errors like this or know how to address them?

**Comment by themelissabrown** [comment]
Hi Armads- Sorry I missed this. I need to improve our workflow for git issues.
If this ever happens again, you can also post in https://gitter.im/highfidelity/hifi or email me directly at melissa@highfidelity.io

I'll draw our internal attention to this now so that we can get you up and running.

**Comment by AndrewMeadows** [comment]
I'm closing this for "VS-2013 is no longer supported".  As I write this the recommended Visual Studio is:  **VS-2017** (for example: Version 15.4.2).
