### ISSUE TITLE
cheatsheet for install in ubuntu 14 - 64 bits

### ISSUE THREAD

**Issue by johnfelipe** [highfidelity/hifi#10973]
Is possible get your help for create a cheasheet for install in linux server side and viewer side in windows
Stay alert

**Comment by sethalves** [comment]
https://github.com/sethalves/hifi-content/tree/master/hifi-linux-server-installation

**Comment by sethalves** [comment]
I went with ubuntu 17 here, because it has, by default, usable Qt packages.  To use older ubuntu I generally have to run Qt's installer and this complicates the recipe.

**Comment by johnfelipe** [comment]
Can I use 14.04?

**Comment by sethalves** [comment]
yeah 14.04 works fine, but the default Qt packages aren't going to work out.  What I end up doing is running the Qt installer on a local linux machine and then rsyncing the resulting Qt directory to the cloud server.  I haven't figured out anything more graceful that that.

**Comment by sethalves** [comment]
To try to be more clear:  I run the installer from http://download.qt.io/official_releases/qt/5.9/ on a Linux machine in front of me (with an X server), install Qt to my a ~/Qt, and then rsync that to the cloud server.  The only real change after that is to set `QT_CMAKE_PREFIX_PATH` to ~/Qt on the cloud server before running cmake.

**Comment by AndrewMeadows** [comment]
Somone: feel free to add an ubuntu-14 cheatsheet here for building/running the hifi code however ubuntu-14 is no longer officially supported, so I'm closing this issue.
