### ISSUE TITLE
Something is causing interface to constantly reconnect [RELEASE-7071]

### ISSUE THREAD

**Issue by CrackerHax** [highfidelity/hifi#11372]
Ubuntu server, windows interface

Symptoms: Interface is repeatedly kicked and tries to reconnect again.
Fix: Stop all scripts [EDIT] Not a fix. Just causes reconnect sound to stop playing.

Check this thread for more info:
https://forums.highfidelity.com/t/cant-connect-to-my-server/13117/5

Also mentioned here:
https://botbot.me/freenode/highfidelity/2016-11-10/?page=1

**Comment by CrackerHax** [comment]
So stopping all scripts is not a fix. That only stops the reconnection sound from playing. It is still constantly reconnecting.

**Comment by sethalves** [comment]
Does this happen with any server?

**Comment by CrackerHax** [comment]
I don't know what the deal is man. It's not even doing it now. I am wondering if it has something to do with lag maybe? I am stumped! If it happens again I will add info here. It seems to have happened to others in the past so maybe this story isn't over, but let's hope it is!
