### ISSUE TITLE
New build errors

### ISSUE THREAD

**Issue by jmo7** [highfidelity/hifi#11386]
I just pulled the latest git code (Sept 18,  18:10 UTC) and tried building on Mint Linux 18.2. I've been using and building hifi on this box for months now and it's been fine. Now I get the following:

In file included from /mnt/hd2/HiFi/hifi/libraries/entities-renderer/src/RenderableModelEntityItem.cpp:12:0:
/mnt/hd2/HiFi/hifi/libraries/entities-renderer/src/RenderableModelEntityItem.h: In member function ‘virtual void RenderableModelEntityItem::computeShapeInfo(ShapeInfo&)’:
/mnt/hd2/HiFi/hifi/libraries/entities-renderer/src/RenderableModelEntityItem.h:49:18: error: ‘ModelPointer ModelEntityWrapper::_model’ is private
     ModelPointer _model;
                  ^
In file included from /usr/include/c++/5/cassert:43:0,
                 from /mnt/hd2/HiFi/hifi/libraries/animation/src/AnimVariant.h:14,
                 from /mnt/hd2/HiFi/hifi/libraries/animation/src/AnimNode.h:22,
                 from /mnt/hd2/HiFi/hifi/libraries/animation/src/Rig.h:24,
                 from /mnt/hd2/HiFi/hifi/libraries/render-utils/src/Model.h:36,
                 from /mnt/hd2/HiFi/hifi/libraries/entities-renderer/src/RenderableModelEntityItem.h:22,
                 from /mnt/hd2/HiFi/hifi/libraries/entities-renderer/src/RenderableModelEntityItem.cpp:12:
/mnt/hd2/HiFi/hifi/libraries/entities-renderer/src/RenderableModelEntityItem.cpp:322:16: error: within this context
         assert(_model && _model->isLoaded() && _compoundShapeResource && _compoundShapeResource->isLoaded());
                ^
In file included from /mnt/hd2/HiFi/hifi/libraries/entities-renderer/src/RenderableModelEntityItem.cpp:12:0:
/mnt/hd2/HiFi/hifi/libraries/entities-renderer/src/RenderableModelEntityItem.h:49:18: error: ‘ModelPointer ModelEntityWrapper::_model’ is private
     ModelPointer _model;
                  ^
In file included from /usr/include/c++/5/cassert:43:0,
                 from /mnt/hd2/HiFi/hifi/libraries/animation/src/AnimVariant.h:14,
                 from /mnt/hd2/HiFi/hifi/libraries/animation/src/AnimNode.h:22,
                 from /mnt/hd2/HiFi/hifi/libraries/animation/src/Rig.h:24,
                 from /mnt/hd2/HiFi/hifi/libraries/render-utils/src/Model.h:36,
                 from /mnt/hd2/HiFi/hifi/libraries/entities-renderer/src/RenderableModelEntityItem.h:22,
                 from /mnt/hd2/HiFi/hifi/libraries/entities-renderer/src/RenderableModelEntityItem.cpp:12:
/mnt/hd2/HiFi/hifi/libraries/entities-renderer/src/RenderableModelEntityItem.cpp:322:26: error: within this context
         assert(_model && _model->isLoaded() && _compoundShapeResource && _compoundShapeResource->isLoaded());
                          ^
In file included from /mnt/hd2/HiFi/hifi/libraries/entities-renderer/src/RenderableModelEntityItem.cpp:12:0:
/mnt/hd2/HiFi/hifi/libraries/entities-renderer/src/RenderableModelEntityItem.h:49:18: error: ‘ModelPointer ModelEntityWrapper::_model’ is private
     ModelPointer _model;
                  ^
In file included from /usr/include/c++/5/cassert:43:0,
                 from /mnt/hd2/HiFi/hifi/libraries/animation/src/AnimVariant.h:14,
                 from /mnt/hd2/HiFi/hifi/libraries/animation/src/AnimNode.h:22,
                 from /mnt/hd2/HiFi/hifi/libraries/animation/src/Rig.h:24,
                 from /mnt/hd2/HiFi/hifi/libraries/render-utils/src/Model.h:36,
                 from /mnt/hd2/HiFi/hifi/libraries/entities-renderer/src/RenderableModelEntityItem.h:22,
                 from /mnt/hd2/HiFi/hifi/libraries/entities-renderer/src/RenderableModelEntityItem.cpp:12:
/mnt/hd2/HiFi/hifi/libraries/entities-renderer/src/RenderableModelEntityItem.cpp:411:16: error: within this context
         assert(_model && _model->isLoaded());
                ^
In file included from /mnt/hd2/HiFi/hifi/libraries/entities-renderer/src/RenderableModelEntityItem.cpp:12:0:
/mnt/hd2/HiFi/hifi/libraries/entities-renderer/src/RenderableModelEntityItem.h:49:18: error: ‘ModelPointer ModelEntityWrapper::_model’ is private
     ModelPointer _model;
                  ^
In file included from /usr/include/c++/5/cassert:43:0,
                 from /mnt/hd2/HiFi/hifi/libraries/animation/src/AnimVariant.h:14,
                 from /mnt/hd2/HiFi/hifi/libraries/animation/src/AnimNode.h:22,
                 from /mnt/hd2/HiFi/hifi/libraries/animation/src/Rig.h:24,
                 from /mnt/hd2/HiFi/hifi/libraries/render-utils/src/Model.h:36,
                 from /mnt/hd2/HiFi/hifi/libraries/entities-renderer/src/RenderableModelEntityItem.h:22,
                 from /mnt/hd2/HiFi/hifi/libraries/entities-renderer/src/RenderableModelEntityItem.cpp:12:
/mnt/hd2/HiFi/hifi/libraries/entities-renderer/src/RenderableModelEntityItem.cpp:411:26: error: within this context
         assert(_model && _model->isLoaded());
                          ^
libraries/entities-renderer/CMakeFiles/entities-renderer.dir/build.make:232: recipe for target 'libraries/entities-renderer/CMakeFiles/entities-renderer.dir/src/RenderableModelEntityItem.cpp.o' failed
make[2]: *** [libraries/entities-renderer/CMakeFiles/entities-renderer.dir/src/RenderableModelEntityItem.cpp.o] Error 1
CMakeFiles/Makefile2:3831: recipe for target 'libraries/entities-renderer/CMakeFiles/entities-renderer.dir/all' failed
make[1]: *** [libraries/entities-renderer/CMakeFiles/entities-renderer.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Menithal** [comment]
Yeah I've seen this also occur on my Debian Server machine.

**Comment by sethalves** [comment]
https://github.com/highfidelity/hifi/pull/11395

**Comment by jherico** [comment]
looks like this will only happen in debug mode.  When I made the change that triggered this failure looks like I didn't build in debug and so missed some asserts that were relying on the old model visibility.

**Comment by AndrewMeadows** [comment]
I closed #11395.  @jherico will fix the build in a more correct way.

**Comment by renanyoy** [comment]
same for me on elementary OS 0.4.1

**Comment by AndrewMeadows** [comment]
I'm closing this for **fixed**.  As I write this: the hifi codebase successfully builds in **release** and **debug** on **ubuntu-18.04** using **g++-7.3.0**.
