### ISSUE TITLE
Compile failure on Ubuntu 16.04 LTS while making assignment-client

### ISSUE THREAD

**Issue by Konshu** [highfidelity/hifi#11446]
Running `make assignment-client && make domain-server` and returned an error below:

`[ 20%] Building CXX object libraries/networking/CMakeFiles/networking.dir/src/OAuthNetworkAccessManager.cpp.o
/home/hifi/hifi/libraries/networking/src/OAuthNetworkAccessManager.cpp: In member function ‘virtual QNetworkReply* OAuthNetworkAccessManager::createRequest(QNetworkAccessManager::Operation, const QNetworkRequest&, QIODevice*)’:
/home/hifi/hifi/libraries/networking/src/OAuthNetworkAccessManager.cpp:40:43: error: ‘FollowRedirectsAttribute’ is not a member of ‘QNetworkRequest’
         authenticatedRequest.setAttribute(QNetworkRequest::FollowRedirectsAttri
                                           ^
libraries/networking/CMakeFiles/networking.dir/build.make:974: recipe for target 'libraries/networking/CMakeFiles/networking.dir/src/OAuthNetworkAccessManager.cpp.o' failed
make[3]: *** [libraries/networking/CMakeFiles/networking.dir/src/OAuthNetworkAccessManager.cpp.o] Error 1
CMakeFiles/Makefile2:463: recipe for target 'libraries/networking/CMakeFiles/networking.dir/all' failed
make[2]: *** [libraries/networking/CMakeFiles/networking.dir/all] Error 2
CMakeFiles/Makefile2:227: recipe for target 'assignment-client/CMakeFiles/assignment-client.dir/rule' failed
make[1]: *** [assignment-client/CMakeFiles/assignment-client.dir/rule] Error 2
Makefile:210: recipe for target 'assignment-client' failed
make: *** [assignment-client] Error 2`

**Comment by WolfGangS** [comment]
What version of QT have you got, and which release of the client are you attempting to build?

**Comment by Konshu** [comment]
QMake version 3.0
Using Qt version 5.5.1 in /usr/lib/x86_64-linux-gnu

I was specifically focusing on bringing up the domain-server tbh.

**Comment by WolfGangS** [comment]
the current versions of HiFi require QT 5.9.1
The best way to get the required CMAKE files is to use the installer for the QT studio set, then take the files you need.

**Comment by Konshu** [comment]
I am going to have to find a way to script around that long term, build a installer script hopefully if I can get this working consistently. 


[ 58%] Linking CXX executable ice-server
[ 58%] Built target ice-server
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2


most current error, looking into what is tripping it up.

**Comment by AndrewMeadows** [comment]
Closing this issue.  The problem appears to be Qt version mismatch.

As I write this the required Qt version is:  Qt-5.10.0

For best results: install Qt in `$HOME` or some known system-wide location via Qt's downloadable installer, then setup the `QT_CMAKE_PREFIX_PATH` environment variable accordingly.  For example, on my xubuntu-18.04 system it is done from the `$HOME.bashrc` file:
```
export QT_CMAKE_PREFIX_PATH="$HOME/Qt/5.10.1/gcc_64/lib/cmake"
```
