### ISSUE TITLE
Memory does not appear to be released on script reload

### ISSUE THREAD

**Issue by DaveDubUK** [highfidelity/hifi#11769]
Whilst experimenting with loading large amounts of animation data (~300MB) into a script, it was noticed that Interface does not appear to be releasing memory on script reload. 

Please see here for a demonstration: https://youtu.be/_VzuOJxZZk0

**Comment by ctrlaltdavid** [comment]
https://github.com/highfidelity/hifi/pull/13345

**Comment by SamGondelman** [comment]
resolved by 13345
