### ISSUE TITLE
Audio input and output list empty with Qt 5.10.0

### ISSUE THREAD

**Issue by ChristophHaag** [highfidelity/hifi#11963]
On Archlinux. They recently updated to Qt 5.10.0.

Screenshots:

Qt 5.9.3
![2017-12-12-000712_1170x856_scrot](https://user-images.githubusercontent.com/781076/33858662-cdf88638-ded0-11e7-889d-9c753e39ae18.png)

Qt 5.10.0
![2017-12-12-000837_1272x687_scrot](https://user-images.githubusercontent.com/781076/33858672-d419243c-ded0-11e7-98eb-552fc2a022dd.png)

**Comment by sethalves** [comment]
https://github.com/highfidelity/hifi/pull/12038

**Comment by sethalves** [comment]
to test:
- https://highfidelity.testrail.net/index.php?/cases/view/145&group_by=cases:section_id&group_order=asc&group_id=1447
- https://highfidelity.testrail.net/index.php?/cases/view/7047&group_by=cases:section_id&group_order=asc&group_id=1450

**Comment by ChristophHaag** [comment]
Thanks, did `git cherry-pick fd4edd2811ab6ce552ffceac6253950e11b2f32c` and the audio menu works. (using https://github.com/ChristophHaag/hifi/commits/master based on the latest stable beta)
