### ISSUE TITLE
Ubuntu 16.04 - CMake version conflict

### ISSUE THREAD

**Issue by FlameSoulis** [highfidelity/hifi#14171]
As of 0.72, the version of cmake needed to build HighFidelity has gone from **3.3.2** to **3.9** (This was updated as far back as PR #11063, but did not seem to affect the building process until 0.72). For Ubuntu 17.04 and Ubuntu 18.04, this is not a problem (cmake-3.9.1 and [cmake-3.10.2](https://packages.ubuntu.com/bionic/cmake) respectively), but Ubuntu 16.04 only goes as far as [cmake-3.5.1](https://packages.ubuntu.com/xenial/cmake) and Ubuntu 17.04 has reached end of live.

The question is how should the documentation be updated, as there are 4 possible routes this can be fixed:

### 1. Build it yourself
   Which isn't too bad but does require following a build guide inside a build guide
### 2. Install from python-pip:
   `sudo apt-get install python-pip`
   `sudo pip install --upgrade cmake`
### 3. Install from cmake.org
   ~~This requires a few extra steps due to a lack of an install feature.~~
   ~~`wget https://cmake.org/files/v3.9/cmake-3.9.6-Linux-x86_64.tar.gz`~~
   ~~`tar -xvf cmake-3.9.6-Linux-x86_64.tar.gz`~~
   ~~`cd cmake-3.9.6-Linux-x86_64`~~
   ~~`sudo cp -r bin /usr/`~~
   ~~`sudo cp -r share /usr/`~~
   ~~`sudo cp -r doc /usr/share/`~~
   ~~`sudo cp -r man /usr/share/`~~
   ~~`cd ..`~~
   ~~`sudo rm -r cmake-3.9.6-Linux-x86_64`~~
   ~~`sudo rm cmake-3.9.6-Linux-x86_64.tar.gz`~~
   Okay, there's a far better way than that:
   `wget https://cmake.org/files/v3.9/cmake-3.9.5-Linux-x86_64.sh`
   `sudo sh cmake-3.9.5-Linux-x86_64.sh --prefix=/usr/local --exclude-subdir`
### 4. HighFidelity includes their own deb repository file like qt5
   This would help resolve the issue entirely if it was offered.
   `wget http://debian.highfidelity.com/pool/h/hi/hificmake_3.9.6.deb`
   `sudo dpkg -i hificmake_3.9.6.deb`

**Comment by FlameSoulis** [comment]
Also, for concept number 1, it'd be:
`wget https://cmake.org/files/v3.9/cmake-3.9.6.tar.gz`
`tar -xvf cmake-3.9.6.tar.gz`
`cd cmake-3.9.6`
`./bootstrap -- -DCMAKE_BUILD_TYPE:STRING=Release`
`make`
`sudo make install`

This is based on https://cmake.org/install/.

**Comment by FlameSoulis** [comment]
As mentioned in #14177, this does also affect server building, as Glad45 is somehow a part of building the server components. If it isn't supposed to, then some tweaking to the building process may be needed, since I can only see its requirements being involved with the gl libraries.

**Comment by shanzzam** [comment]
manuscript ticket  https://highfidelity.manuscript.com/f/cases/19225/Ubuntu-16-04-CMake-version-conflict

**Comment by shanzzam** [comment]
https://github.com/highfidelity/hifi/pull/15029 resolved this
