### ISSUE TITLE
CMAKE Minimum Required not checked

### ISSUE THREAD

**Issue by FlameSoulis** [highfidelity/hifi#14177]
As of Glad45's inclusion in the building process, it has the following line:
```
cmake_minimum_required(VERSION 3.6)
```
I've been building the server components on Ubuntu 16.04, which had 3.5.1 by default. As the build guide states the requirement is 3.9, why isn't this checked for in the building process? This is what is the primary cause of concern for issue #14171.

Should the following line be added to the main CMakeLists.txt?
```
cmake_minimum_required(VERSION 3.9)
```

**Comment by shanzzam** [comment]
related to https://highfidelity.manuscript.com/f/cases/19225/Ubuntu-16-04-CMake-version-conflict

**Comment by NissimHadar** [comment]
It seems to be safer to change the appropriate readme's to *Go get the latest release version of CMake*.

I would rather not enforce a higher limit in the CMake file, so as not to force changes to the Jenkin images.

**Comment by shanzzam** [comment]
Addressed with this PR https://github.com/highfidelity/hifi/pull/15029
