### ISSUE TITLE
Bookmarks stores garbage data on soft attachments

### ISSUE THREAD

**Issue by FlameSoulis** [highfidelity/hifi#14285]
While looking into thumbnail stuff on bookmarks, I realized that if an avatar has a soft attachment, it will have a large amount of garbage data, namely the storage of the joint rotations and positions (which is made worse by the red/green/blue issue on all vectors). This can dramatically increase the size of an avatar bookmark, which can be made worse if someone decides to have an outfit of varying clothing materials.

[garbage_bookmark.txt](https://github.com/highfidelity/hifi/files/2521099/garbage_bookmark.txt)

**Comment by shanzzam** [comment]
Opened internal ticket for this 
https://highfidelity.manuscript.com/f/cases/19618/Soft-attachments-on-Avatar-s-contain-too-much-data

Linking back here and will update this PR for status.

**Comment by shanzzam** [comment]
PR for this https://github.com/highfidelity/hifi/pull/14488
Merged into 77.

**Comment by shanzzam** [comment]
Merged
