### ISSUE TITLE
102MB compound file is crashing interface.exe

### ISSUE THREAD

**Issue by Richardus** [highfidelity/hifi#7822]
Trying to make walkable terrain. Overdoing it a bit in scale. terrain is 30710x30710 meters.
Just made a compound shape in blender. upload that into ATP , as soon you copy the atp url in the compound box of the terrain file. interface is crashing !

The terrain file can be downloaded from here. (3.5MB)
https://app.box.com/s/i6z15l6we0vmbvp1fufdwsuxs0elrs51

And the compound file can be downloaded from here for testing and checking. (102MB)
https://app.box.com/s/dbvpwpu2029pm13jrsh7a9ijtfgcsw3d

Windows 10 , build 4825

**Comment by Atlante45** [comment]
Hi @Richardus,
I just checked what was going on and basically, your collision hull has almost 1M triangles.
I'm afraid this is just way too much and we can't handle such a big hull at the moment.

**Comment by AlanZimmerman** [comment]
Clement is right, it's just too big to really work with right now. Also, each compound hope has to be separated into its own layer in Blender. You can do this from edit mode by clicking 'a' to select all, then 'p' and choosing 'separate by loose parts'. Beware though, if your model has more than 10-15k loose parts, Blender will stall and need to be restarted.

I went ahead and scaled back the poly could of your original fbx, and then created a compound shape from it for you. It's not going to match up exactly at that scale, but it should at least work:

http://hifi-content.s3.amazonaws.com/alan/dev/support/Terrain-20160505-001b1-comp-AZ.obj

**Comment by Richardus** [comment]
I agree, 102MB is way over what i call acceptable. But just wanted to test it to see what happens. And it's a nice test file. Already start to feel bad with a file that is 10MB in size.

Thanks Alan, going to test your compound,
