### ISSUE TITLE
Controller API should the ability to call vibrate event.

### ISSUE THREAD

**Issue by Menithal** [highfidelity/hifi#7844]
Controller API should have some capacity to vibrate the controllers for a certain length of time and specific intensities.

**Comment by SamGondelman** [comment]
@Menithal this functionality has been added (although it only works on vive right now).  Let me know if there's anything else you want for this, otherwise feel free to close the issue :D

**Comment by Menithal** [comment]
Sorry, took a bit to notice this was commented.  This has been implemented. Cant wait to try it out on the hookguns :)
