### ISSUE TITLE
Close interface.exe while it's starting is lockup.

### ISSUE THREAD

**Issue by Richardus** [highfidelity/hifi#7857]
Interface (build  4864). Where starting on windows 10 64bit when i closed very quick at startup the [X] button. This results in complete lockup of interface and it stops responding. If you press thge [X] again windows comes back with crash window. No dang !
- Open interface.exe
- Press the [X] before it get the time to load the world or icons.
- It's locking up the system here.

**Comment by hyperlogic** [comment]
We've fixed a lot of issues related to crashing/closing on startup.  Please re-open this issue if it is still occurring.
