### ISSUE TITLE
Can no longer set color on "image" overlays

### ISSUE THREAD

**Issue by ctrlaltdavid** [highfidelity/hifi#7883]
You used to be able to set the color of an "image" overlay, e.g., set the color of SVGs used in users.js.
Now instead the following is reported in the program log when users.js starts up:
OVERLAY Unhandled image property color

**Comment by SamGondelman** [comment]
This appears to work now:
```
var overlay = Overlays.addOverlay("image", {
    x: 100,
    y: 100,
    width: 100,
    height: 100,
    imageURL: "https://mario.nintendo.com/assets/img/home/intro/mario-pose2.png",
    color: { red: 255, blue: 0, green: 0}
});
```
