### ISSUE TITLE
Interface crashes / UI instabilities under Linux

### ISSUE THREAD

**Issue by OrionPseudo** [highfidelity/hifi#7903]
Experiencing various UI instabilities and crashes while running interface under Linux.  General rendering / movement appears to work fine, however accessing various menu items and dialogs nearly always results in a crash / segmentation fault. 

- See attached logs for details.

Built from Master @ 87aa90de0800bd71aed87ed4ba1bb3f0aacc6324 - Sat May 14 09:12:16 2016 -0700
Linux / Ubuntu 16.04 (amd64) - same behavior previously on Ubuntu 15.10 and OpenSuse Leap.
Tried stock QT5.5 installed in /opt, currently building off of the hifi-qt package from debian.highfidelity.com

[[Crash after settings -> general closed then hovered mouse over settings menu] hifi-log.txt](https://github.com/highfidelity/hifi/files/264760/Crash.after.settings.-.general.closed.then.hovered.mouse.over.settings.menu.hifi-log.txt)

[[Crash after settings -> avatar opened and closed, then hovered mouse over settings menu] hifi-log.txt](https://github.com/highfidelity/hifi/files/264759/Crash.after.settings.-.avatar.opened.and.closed.then.hovered.mouse.over.settings.menu.hifi-log.txt)

[[Crash after setting audio devices and then opening examples window] hifi-log.txt](https://github.com/highfidelity/hifi/files/264758/Crash.after.setting.audio.devices.and.then.opening.examples.window.hifi-log.txt)

[[Crash after changing avatar display name then setting avatar model URL] hifi-log.txt](https://github.com/highfidelity/hifi/files/264757/Crash.after.changing.avatar.display.name.then.setting.avatar.model.URL.hifi-log.txt)

[CMakeCache.txt](https://github.com/highfidelity/hifi/files/264769/CMakeCache.txt)

[[Crash after teleport from playa to pseudospace while scene was loading] hifi-log.txt](https://github.com/highfidelity/hifi/files/264768/Crash.after.teleport.from.playa.to.pseudospace.while.scene.was.loading.hifi-log.txt)

**Comment by sethalves** [comment]
I also get a lot of UI related crashes on Linux.  Maybe try this:

export HIFI_MEMORY_DEBUGGING=1
and then do a clean rebuild.  This will enable asan and can give much better crash information.  You may have to delete the shared libraries in the plugins directory to run.

**Comment by OrionPseudo** [comment]
Thanks sethalves!  That certainly does provide an awful lot more useful info.  I've re-traced my steps and recreated (most) of the crashes from the past logs while on that same commit.  The latest commits from today seem to produce a crash straight at startup, so I'll wait for things to settle down before pulling and retrying. From the looks of it with the exception of whatever the quirk is with the examples window, most of the crashes seem to be something to do with fonts?

[[Crash after setting audio devices then opening examples window] hifi-log.txt](https://github.com/highfidelity/hifi/files/267289/Crash.after.setting.audio.devices.then.opening.examples.window.hifi-log.txt)

[[Crash after setting display name then setting avatar model] hifi-log.txt](https://github.com/highfidelity/hifi/files/267290/Crash.after.setting.display.name.then.setting.avatar.model.hifi-log.txt)

[[Crash after settings -> avatar opened and closed then hovered mouse over settings menu] hifi-log.txt](https://github.com/highfidelity/hifi/files/267293/Crash.after.settings.-.avatar.opened.and.closed.then.hovered.mouse.over.settings.menu.hifi-log.txt)

[[Crash after settings -> general opened and closed then hovered mouse over settings menu.] hifi-log.txt](https://github.com/highfidelity/hifi/files/267294/Crash.after.settings.-.general.opened.and.closed.then.hovered.mouse.over.settings.menu.hifi-log.txt)

[[No Crash - Teleport from Pseudospace to Playa and back]  hifi-log.txt](https://github.com/highfidelity/hifi/files/267295/No.Crash.-.Teleport.from.Pseudospace.to.Playa.and.back.hifi-log.txt)

[CMakeCache.txt](https://github.com/highfidelity/hifi/files/267296/CMakeCache.txt)

**Comment by OrionPseudo** [comment]
Interesting discovery! As of Master @ https://github.com/highfidelity/hifi/commit/8ad572a269a83809171a8e0310599a29659ebdde I found that if I delete the contents of the plugins folder before launching, most of the UI glitches seem to clear up with the exception of the issue with the examples window.  

Whatever is causing this seems related to the plugins.  If either libhifiSixense.so
 or libhifiSixense.so remain in that folder when the interface is launched, all of the issues return.

**Comment by OrionPseudo** [comment]
As of https://github.com/highfidelity/hifi/commit/bbe9b931bee9364581feb1ab983de329f7d0c301 - https://github.com/highfidelity/hifi/pull/8141 this issue seems to be resolved.
