### ISSUE TITLE
Rendering: Roughness texture only takes 6.25% increments.

### ISSUE THREAD

**Issue by Menithal** [highfidelity/hifi#7911]
Putting this on the issues since this been a long standing issues from the forums, and it may have been buried with alot of logs (and due to lack of asana link, or access there, I cant really see if the issue has been logged)

Here I have a test object to replicate this
http://www.norteclabs.com/HF/experiment/RoughnessGradient2.fbx
It has the following texture applied to it as roughness
![Image of Dither texture](http://www.norteclabs.com/HF/experiment/dithergradient.png)
It should have approximately 0.39% difference per level.

However, inengine this is rendered as

![Image of Dither texture](https://cdn-business.discourse.org/uploads/highfidelity/original/2X/6/674e17c260cf7bd0d959bb6c5056ab55329c9665.gif)

Defined as 6,25% thresholds. This means loss of detail regardless of the roughness / glossiness definition and textures can ONLY define about 16 roughness states at the moment.

**Comment by samcake** [comment]
@Menithal this one is for you
https://github.com/highfidelity/hifi/pull/10014

**Comment by samcake** [comment]
Done
