### ISSUE TITLE
Rendering: Shiny objects that reflect environment jitter when head is moved in mouselook and in HMD

### ISSUE THREAD

**Issue by Menithal** [highfidelity/hifi#7913]
Some metallic defined objects that reflect the environment map that are flat jitter alot when the camera is rotated even slightly when they are visible. Effects are ridiculously compounded when using an HMD. 
http://www.norteclabs.com/HF/experiment/roughness.fbx

![](http://www.norteclabs.com/HF/gif/jitter.gif)

**Comment by hyperlogic** [comment]
This was fixed in #7995
