### ISSUE TITLE
gcc-6.x fatal error: math.h: No such file or directory

### ISSUE THREAD

**Issue by ChristophHaag** [highfidelity/hifi#8047]
gcc 6.1 on Archlinux

```
In file included from /home/chris/oldhome/build/hifi/build/ext/makefiles/glm/project/include/glm/detail/_fixes.hpp:29:0,
                 from /home/chris/oldhome/build/hifi/build/ext/makefiles/glm/project/include/glm/glm.hpp:78,
                 from /home/chris/oldhome/build/hifi/hifi/libraries/shared/src/Plane.h:18,
                 from /home/chris/oldhome/build/hifi/hifi/libraries/shared/src/Plane.cpp:15:
/usr/include/c++/6.1.1/cmath:45:23: fatal error: math.h: No such file or directory
```

Apparently it has to do with the usage of -isystem combined with gcc 6.x:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71090
https://stackoverflow.com/questions/37218953/isystem-on-a-system-include-directory-causes-errors

It's used in two CMake files: https://github.com/highfidelity/hifi/search?q=-isystem&type=Code&utf8=%E2%9C%93

**Comment by ChristophHaag** [comment]
Since cuda requires gcc 5, there's a gcc5 package in archlinux.
Building with
```
CC=/usr/bin/gcc-5 CXX=/usr/bin/g++-5 cmake .
```
works.

So it's broken since gcc 6.

**Comment by abhiAB23** [comment]
Solution is Simple...
1: just go to usr/include/c++
2: chose whatever version you are using. In my case it was 6, So chose folder 6
3: look for cmath.c and open it. Change "#include_next <math.h>" to "#include<math.h>" 
4: Save it and Done..

If you are having error with stdlib.h then also do the same for "cstdlib.c" file

**Comment by ChristophHaag** [comment]
I did not retest gcc 6, but with 7.2.0 it builds fine now.

**Comment by kroumann** [comment]
@abhiAB23  you saved me after 3 days of debug 1000 thanks...

**Comment by AISayeh** [comment]
@abhiAB23 Thanks bro
