### ISSUE TITLE
canRezTmp logic (incorrectly) resets valid lifetimes to the maximum value

### ISSUE THREAD

**Issue by humbletim** [highfidelity/hifi#8159]
With the latest canRezTmp changes #8118, it no longer seems possible for tmp-rez nodes to create *short-lived* Entities with an initial velocity.

This affects things like the Ping Pong Gun which will now shoot balls surviving for a full hour, despite being programmed with a 10 second lifetime.

Attached is a test script to demonstrate the issue along with its output from Playa.  I get the same results using a fresh build of master on localhost as well.

In the below output, each "requested" value is the lifetime passed to `Entities.addEntity` and the "reported" value is what was returned 5 seconds later from `Entities.getEntityProperties`:
 
```text
[DEBUG] script:print()<< hostname:   Playa
[DEBUG] script:print()<< canRez:     false
[DEBUG] script:print()<< canRezTmp:  true
[DEBUG] script:print()<< requested: undefined  / reported: 3600
[DEBUG] script:print()<< requested: -1  / reported: 3600
[DEBUG] script:print()<< requested: 0  / (deleted)
[DEBUG] script:print()<< requested: 1  / reported: 3600
[DEBUG] script:print()<< requested: 3  / reported: 3600
[DEBUG] script:print()<< requested: 5  / reported: 3600
[DEBUG] script:print()<< requested: 3600  / reported: 3600
[DEBUG] script:print()<< requested: 3601  / reported: 3600
```

The expected behavior is for valid lifetime values to get applied and then remain preserved throughout an Entity's natural existence -- regardless of initial velocity (or any other nonscripted physical interactions).

[canRezTmpTests.js.txt](https://github.com/highfidelity/hifi/files/338816/canRezTmpTests.js.txt)

**Comment by sethalves** [comment]
initial velocity is required to demonstrate this bug?

**Comment by humbletim** [comment]
well, that's just the easiest way to demonstrate.

another way is to create an Entity with `dynamic: true` and then collide your avatar into it, which also causes that Entity's lifetime to be reset to 3600.

seems to have something to do with physics simulation and the moments in time/change that the constraint is being checked.

from what i can tell the actual Entity lifetime isn't available to the constraint logic (when its checking) -- so instead `getLifetime()` returns the default of -1 (immortality), which is considered invalid and leads to a reset.

here's the testing snippet again as a gist; it's set up to demonstrate the initial velocity case, but changing the properties template it works for staging the collision case as well:
https://gist.github.com/humbletim/2672449fd7efd120ec68a0d7ab91bf0a#file-canrestmptests-js

**Comment by humbletim** [comment]
... this bug also seems to have a "touch of death" side effect where physical activation of certain kinds of older (age > 3600), immortal (lifetime == -1) Entities can cause them to be nuked on the spot. :fearful:

**Comment by sethalves** [comment]
okay, I'll try to take a look at this, this afternoon.

**Comment by humbletim** [comment]
ok.  not entirely sure if this is useful but had a random idea -- what if negative lifetimes were used to make temporary status a more explicit and independent quality from domain max tmp?

like a temporary Entity living for 1 second would be encoded internally as lifetime=-2, or for ten seconds as lifetime=-11, etc.

the tilde bitwise operator could help keep logic still relative-free of conversion pains:   
```c++
bool immortal = !~lifetime; // ~(-1) == 0
bool stable = lifetime > 0;
bool temporary = ~lifetime > 0; // ~(-2) == 1, ~(-3) == 2, etc.

if (!immortal) {
  if (stable && (age + lifetime) > now) { /* kill it */ } 
  else if (temporary && (age + ~lifetime) > now) { /* kill it */ }
}
 ```

in this way temporary Entities never overlap with immortal and stable ones (in terms of lifetime values or wall clocks) -- and the domain max tmp setting is no longer needed to make an initial judgement call as to whether an Entity is temporary or not (which is probably the only kind of existing Entity a tmp-rez node should be thinking about editing in the first place?).

**Comment by humbletim** [comment]
the #8172 PR fix appears to do the trick!  (closing this issue in favor of tracking the PR)
