### ISSUE TITLE
Crash: Closing Asset Browser causes a crash on 5086

### ISSUE THREAD

**Issue by Menithal** [highfidelity/hifi#8165]
## Repro:

Open up Asset Browser
Upload a new asset
Browser and Select an asset 
Notice Asset File Browser not going away on Selection
Close Asset Browser Manually
Crash

## Expected

Should close Automatically after selecting Asset, Similarly if you choose to ignore the File browser and press upload asset

**Comment by ctrlaltdavid** [comment]
@Menithal I can't seem to reproduce this on build 5086.

"Browse and Select an asset" = click on asset entry in Asset Directory window; then click "Add to World" button?

**Comment by ctrlaltdavid** [comment]
https://github.com/highfidelity/hifi/pull/8336

**Comment by ctrlaltdavid** [comment]
Fixed in build 5233
