### ISSUE TITLE
Lifespan of Entities keeps forced to 1 hour

### ISSUE THREAD

**Issue by Menithal** [highfidelity/hifi#8241]
It seems I cannot set it any lower than that via anything.  Its keeps resetting it self to 3600 on Domains I only have temporary object creation rights.

I should be able to set and change an objects lifespan all the way to an hour, to make sure the object is cleaned up, even if a agent that controls it crashes, or disconnects.

**Comment by sethalves** [comment]
It seems like I'm able to set lower lifetimes with edit.js.  Could you list the steps needed to demonstrate this bug?

**Comment by Menithal** [comment]
Yeah you can lower the lifetime with edit.js. However as soon as you modify any other settings, the lifetime resets to 3600s.

**Comment by Menithal** [comment]
Another way to repeat this is just to make a dynamic box, and trying to set lifetime on it. It sets it for a few seconds before updating back to 3600s.

**Comment by sethalves** [comment]
I'm still not seeing it.  With a tmp-rez-only account, I create a box, make it dynamic, and change its lifetime from 3600 to 600.  I edit other things, wait, bump the box.  The lifetime stays 600.

**Comment by sethalves** [comment]
Okay, maybe I see what's happening.  Are you using the  "Beta 5111 | Released 6 JUL, 2016"?  https://github.com/highfidelity/hifi/pull/8172 isn't in that one (but will be in the next one... released later today?)

**Comment by Menithal** [comment]
Yes this is 5111 bug.
