### ISSUE TITLE
Overlays.getProperty broken

### ISSUE THREAD

**Issue by CrackerHax** [highfidelity/hifi#8338]
var e = Overlays.addOverlay("text", {
	x: 300, y: 100, width: 10, height: 10 ,
	backgroundColor: { red: 0, green:0, blue:0},
	backgroundAlpha: 0.0,
	visible:false,
	text: "Hello, world!",
	alpha: 0.0
    });

    var n = Overlays.getProperty(e, "text");
	print(n);

produces:
     [07/30 09:47:10] [DEBUG] script:print()<< undefined

**Comment by ctrlaltdavid** [comment]
You used to be able to do this but apparently can't now "by design": no properties can be retrieved from QML-based overlays, i.e., 2D overlays. In the code...
    // Cannot fetch properties from QML based overlays due to race conditions

**Comment by CrackerHax** [comment]
So it is dead code now and should probably be removed.

**Comment by AlexanderOtavka** [comment]
There is no way to raypick or get the ID of an overlay in a script that is not created by a script.  Therefore it is up to the script to keep track of the overlay's properties whenever it modifies the overlay.  Maybe do something like this:

```
var eProps = {
    x: 300, y: 100, width: 10, height: 10 ,
    backgroundColor: { red: 0, green:0, blue:0},
    backgroundAlpha: 0.0,
    visible:false,
    text: "Hello, world!",
    alpha: 0.0
};

var e = Overlays.addOverlay("text", eProps);

eProps.text = "Foo!";
Overlays.setProperties(e, eProps);

var n = eProps.text;
print(n);
```

**Comment by CrackerHax** [comment]
overlays.setproperties does not exist.
