### ISSUE TITLE
/Path setting not working on localhost

### ISSUE THREAD

**Issue by Richardus** [highfidelity/hifi#8570]
Working on minigolf. wanted to set a zone. That seems to fail on localhost.
i made a new path name "/golf" , but i cannot get to it  "/localhost/golf" is not working.

See also https://forums.highfidelity.com/t/path-not-working-on-localhost-and-skybox-in-zone-problem/11415/3

**Comment by thoys** [comment]
Wouldn't it be localhost/golf without the leading slash ?

**Comment by Richardus** [comment]
Path setting is working on localhost @huffman  explained it in this topic. 
https://forums.highfidelity.com/t/path-not-working-on-localhost-and-skybox-in-zone-problem/11415/6
