### ISSUE TITLE
Provide a __FILE__ like constant to JavaScript

### ISSUE THREAD

**Issue by humbletim** [highfidelity/hifi#8576]
Basically, let the value of `__FILE__` be the *actual URI* that was used to retrieve the current script's contents.

Unlike `Script.resolvePath` (which at the moment seems to work unreliably), `__FILE__` would just be a simple, constant fact about the code -- one that holds true throughout its entire lifetime.

Here is an example of how such a `__FILE__` constant could be put to work -- like as a short term way for Entity Scripts to produce their own relative resource paths: 

```javascript
(function() {
    var re = /[^\/]*$/;
    return {
        preload: function(uuid) {
            this.basename = __FILE__.split('/').pop();

            this._PWD     = Script.resolvePath('.');    // doesn't work! (returns just "file:")
            this.PWD      = __FILE__.replace(re, '');   // works for me...

            Script.include(Script.resolvePath('../helper.js')); // doesn't work! (returns "file:helper.js")
            Script.include(this.PWD + '../helper.js');          // works for me...  

            //print('this', uuid, JSON.stringify(this,0,2));
        },
        clickDownOnEntity: function(uuid) {
            print(
                'eg: resolve a sound file relative to self:',
                __FILE__.replace(re, 'alert.wav')
            );
        }
    };
})
```

**Comment by huffman** [comment]
@humbletim Are you mainly looking for proper resolution of paths? I have a PR here you might be interested in: https://github.com/highfidelity/hifi/pull/8664

**Comment by humbletim** [comment]
@huffman Yeah, mainly -- as long as `resolvePath` returns consistent values now from anywhere/anywhen within a source file then should be good to go.  I'll give the updated function a whirl.

The other aspect I was looking at with `__FILE__` is having a progressive way to differentiate between runtime filename and development filename -- which becomes one-to-many when using a module and packaging system to concatenate lots of scripts together at once into a self-contained bundle.

**Comment by humbletim** [comment]
@huffman tested locally and #8664 appears to work per the change set's intentions...

It's not super critical... but this PR breaks my current way of introducing Entity scripts at a JS101-level:

```javascript
// delegate.js -- entity script

delegate = function delegate(uuid) {
    try { uuid.exists; } catch (e) { e.fileName.replace(/EntityID:([^,]+)/, function(_, id) { uuid=id; }); }

    // "static" initialization using uuid here

    return {
        clickDownOnEntity: function(_, evt) {
            print('delegate.clickDownOnEntity', evt.button);
        },
    };
};
```

While that requires a hack -- the one line of fuss helps avoid introducing the typical JS501+ muss until later (and also makes it easier to introduce things top-down like with PP reveals).

Before this PR it worked fine because UUID was available in the Entity pseudo-filename -- `(EntityID:{22471874-1e93-4b02-bdbc-10861e3b7de3}, file:///hifi/test-Script-include.js)`.

Is there any chance `Script.resolvePath('')` could return the filename, but the internal script identifier could stay the same as before?  Or another way to get at the "a priori" UUID?

(note: it's not the character difference that makes pulling uuid from preload a challenge; think... felt-tip markers tracing program execution flow by hand)

**Comment by humbletim** [comment]
... OK, found a workaround by splitting entity creation into two steps; first doing the add with everything but script url, then tacking-on the returned UUID when setting that -- eg: `Entities.editEntity(entityID, { script: 'delegate.js?EntityID:'+entityID });`

since with the PR `__FILE__` can basically be emulated now using resolvePath, closing this out

**Comment by huffman** [comment]
@humbletim I ended up including the entity id in the filename at the end, example: `http://www.example.com/some/path.js [EntityID:{9fdd355f-d226-4887-9484-44432d29520e}]`

Does that solve your issue? Ideally I'd prefer it not to be in the filename and for us to associate the entity ID with the context in a different way, but there is not an easy path for that currently.

**Comment by humbletim** [comment]
@huffman Awesome, thanks! That helps keep everything else in good alignment.

And I'm with you re: finding better ways than filename.  Maybe some day later could move out of filename and live somehow like `Script.resolvePath('')` as `Entities.getEntityProperties('').id`.

Or even more hypothetically as `MyEntity.id`.

**Comment by huffman** [comment]
@humbletim I just had to remove it temporarily due to a bug, but it will be reintroduced at some point, but in a different format.

re: getting the entity id, you can also get it from the entity `preload(entityID)` function - have you used that before?

**Comment by humbletim** [comment]
@huffman Ahh, OK.

> re: getting the entity id, you can also get it from the entity preload(entityID) function - have you used that before?

Yes.  Appreciate the suggestion and technically `preload` works, just not as well for a downhill path to initially discover, discuss and develop "perceptible" cause/effect relationships inworld (using just entry-level scripting concepts).

To me `preload`'s inherent [impact on complexity](https://gist.github.com/humbletim/623d311abb5361a35a6bacf0277c1ff7#file-readme-md) is just too disruptive in that context.

Anyway, I'm cool using the manual .scriptURL += workaround for now.

If reintroducing again later, maybe a benign way to propagate would be as a hash fragment appended to whatever filename/URL is already there (eg: on the backend `script += "#EntityID:"+uuid;` -- so the combined result remains innocuous in terms of URL parts).
