### ISSUE TITLE
Wrong texture format TGA in this case, make whole mesh entity invisible

### ISSUE THREAD

**Issue by Richardus** [highfidelity/hifi#8578]
WHen you add (by accident) a TGA texture on a face. in your build and upload that mesh entity. In high Fidelity the whole build get invisible. 

Example FBX file with TGA can be downloaded from here. https://app.box.com/s/yjotxukqqpjmagrjk9g6fctrcb3v85re

Instead high fidelity could ignore bad textures and replace it for error texture. But at least make everything else visible and ignore the faces with bad texture in same way.

**Comment by hyperlogic** [comment]
Hmm, that's weird.  The QImageReader class, which we use to read textures, should support TGA files.  I'll take a closer look

**Comment by hyperlogic** [comment]
Yeah, this is a bug, although QImageReader supports TGA, some of our internal code using QImage::fromData() does not.

**Comment by hyperlogic** [comment]
Ok, it's actually that QImageReader does not support Run-Length encoded TGAs.  Uncompressed TGAs work fine.

**Comment by SamGondelman** [comment]
The original attached file isn’t there anymore, but we have TGA support now and it is working in our hifi_tests repo
