### ISSUE TITLE
cmake warning on /tests/physics/src/MeshUtil.cpp

### ISSUE THREAD

**Issue by ctrlaltdavid** [highfidelity/hifi#8579]
On Windows
With clean (empty) build directory...
cmake .. -G "Visual Studio 12 2013 Win64" -DCMAKE_BUILD_TYPE=Release
... generates the following warning:

CMake Warning at cmake/macros/SetupHifiTestCase.cmake:72 (message):
  ignoring .cpp file (not a test class -- this will not be linked or
  compiled!):
  D:/Workspaces/CtrlAltStudio/HiFi/HiFi/tests/physics/src/MeshUtil.cpp
Call Stack (most recent call first):
  tests/physics/CMakeLists.txt:9 (setup_hifi_testcase)

**Comment by AndrewMeadows** [comment]
This was fixed in PR-8740.
