### ISSUE TITLE
Questions: Automatic VR world creation and host.

### ISSUE THREAD

**Issue by dg3kim** [highfidelity/hifi#8802]
Is it possible at the moment to create and host my own VR world and send the links to friends over scripts?

** I am not sure this is the right place to ask questions..
Thanks,

**Comment by birarda** [comment]
Hi @dg3kim! 

We use our Github issues mostly to track public bug reports, but I'll be happy to respond to your question before closing this. I'd also like to invite you to head over to [our forums](https://forums.highfidelity.com/) which will be a good resource to help you get setup and learn some of the possibilities that are offered to you with High Fidelity.

You'll need to decide if you want to build the servers/client from source or simply download an installer. 

If you download High Fidelity (our download page is [here](https://highfidelity.com/download)) it includes the Sandbox, which is the easiest way to host your own VR world (we call them domains). I'm going to assume that you'll be using the Sandbox, but if you'd like different instructions for building from source I can provide them here or you can checkout the README and BUILD guides in the repository.

If you install and run the Sandbox, underneath the hood you'll be running a Domain Server and a number of Assignment Clients. These are the components that handle all that is required to host/run/simulate your High Fidelity domain.

When you run your Sandbox we give you a temporary place name which you can use to have others connect to your domain using High Fidelity Interface (which they can install from the same installer at the download link above). 

There will be a High Fidelity icon in your tray for the Sandbox. If you click on that you will have an option 'Share'. That will open up your Domain Server settings and provide you with a copiable sharable `hifi://` link that includes the temporary place name. You can provide this link to your friends - they can either click on it as a hyperlink in any desktop application to launch Interface or enter it in the Address Bar in Interface to jump to your domain!

I hope this answers your question. I'm going to close this issue but I'll be happy to provide more information if you need.
