### ISSUE TITLE
Allow AC scripts to create ATP assets

### ISSUE THREAD

**Issue by humbletim** [highfidelity/hifi#8918]
Currently AC scripts are initialized without ATP write access.

I would like to submit a PR that adds the permission in:
https://github.com/highfidelity/hifi/compare/master...humbletim:allow-acscript-atp-uploads

My current use case is for procedural model generation.  With ATP write access domain owners could run an AC script on stock builds to dynamically generate FBX assets and serve over ATP.

**Comment by sethalves** [comment]
suggestions for a test plan?

**Comment by humbletim** [comment]
cc #8986
