### ISSUE TITLE
Quat.lookAtSimple in Quat.cpp is missing absolute value restriction

### ISSUE THREAD

**Issue by flipside** [highfidelity/hifi#8964]
Need to take the absolute values of dir.x and dir.z

    // if the direction is nearly aligned with the Y axis, then use the X axis for 'up'
    if (dir.x < 0.001f && dir.z < 0.001f) {
        return lookAt(eye, center, Vectors::UNIT_X);
    }

https://github.com/highfidelity/hifi/blob/master/libraries/script-engine/src/Quat.cpp#L40

**Comment by AndrewMeadows** [comment]
This is fixed in PR-8992:  https://github.com/highfidelity/hifi/pull/8992

**Comment by AndrewMeadows** [comment]
The fix has been merged.
