### ISSUE TITLE
Entity.setAbsoluteJointRotationInObjectFrame uses local rotation

### ISSUE THREAD

**Issue by flipside** [highfidelity/hifi#8965]
`Entities.setAbsoluteJointRotationInObjectFrame` seems to use local rotation relative to parent joint while `Entities.getAbsoluteJointRotationInObjectFrame` seems to get rotation in the object frame. Should probably rename `Entities.setAbsoluteJointRotationInObjectFrame` to `Entities.setLocalJointRotation`. 

Probably applies to `Entities.setAbsoluteJointRotationsInObjectFrame` too.

https://github.com/highfidelity/hifi/blob/master/libraries/entities/src/EntityScriptingInterface.cpp#L1135

**Comment by ZappoMan** [comment]
Thanks for the bug reports Mat, I will file these in our bug tracker.

**Comment by sethalves** [comment]
https://github.com/highfidelity/hifi/pull/8984/files

any suggestions for a test plan?

**Comment by flipside** [comment]
Will you also be adding a real `setAbsoluteJointRotationInObjectFrame` and `setAbsoluteJointTranslationInObjectFrame` along with `getLocalJointRotation` and `getLocalJointTranslation`? Converting between local and global is a pain.

**Comment by sethalves** [comment]
yes, we can add these.  I'll update the PR when I get a chance.

**Comment by sethalves** [comment]
That PR is ready, but still lacks a test plan.  Do you have a script that would work?  If not I can make something simple.
