### ISSUE TITLE
 MyAvatar.getJointPosition not supporting "_CONTROLLER_RIGHTHAND" and "_CONTROLLER_LEFTHAND"

### ISSUE THREAD

**Issue by fayeli** [highfidelity/hifi#8979]
These two joints ("_CONTROLLER_RIGHTHAND" and "_CONTROLLER_LEFTHAND") works for parenting entities/overlays, as seen for little blue grabbing spheres. But when I was hoping I can find their positions, it was always 0,0,0,0. Would be nice to have support for them through the JS API.

Thanks!

For your reference:
![capture](https://cloud.githubusercontent.com/assets/2405697/19910408/f3583160-a049-11e6-9d49-e221ad915f87.PNG)

**Comment by hyperlogic** [comment]
The Controller JS API supports getting the hand controller location.

    var pose = Controller.getPoseValue(Controller.Standard.RightHand);
    var handTranslation = pose.translation;
    var handOrientation = pose.orientation;

Note these are relative to the avatar's current position and rotation.

Alternatively, you can use the following the following calls to get the position of the right and left palms.

    var pose = MyAvatar.getRightHandPose();
    var handTranslation = pose.translation;  // vec3
    var handRotation = pose.rotation;  // quat

See these wiki entries for more info:

https://wiki.highfidelity.com/wiki/GetPoseValue()
https://wiki.highfidelity.com/wiki/GetLeftHandPose()
https://wiki.highfidelity.com/wiki/GetRightHandPose()
