### ISSUE TITLE
Entities.setAbsoluteJointRotationInObjectFrame crashes entity server 

### ISSUE THREAD

**Issue by flipside** [highfidelity/hifi#8981]
Tested this in the scripting console on 5585 and 5629 and both times a few seconds after I `Entities.setAbsoluteJointRotationInObjectFrame(id, index, rotation)` the entity server crashes and then reboots.

**Comment by sethalves** [comment]
Would you be willing to share the entity properties and call parameters?

**Comment by flipside** [comment]
Here's 2 scripts ([no animations](http://hifi-pet.herokuapp.com/scripts/summonDragonJointCrash.js
) and [animatations](http://hifi-pet.herokuapp.com/scripts/summonDragonJointCrashAnimated.js)) that reliably crash my entity server, they both will rotate a single joint 1 second after loading. Also crashes if you rotate the joint in the console. The rotation does work locally though.

**Comment by sethalves** [comment]
https://github.com/highfidelity/hifi/pull/8991

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/2176/Entities-setAbsoluteJointRotationInObjectFrame-crashes-entity-server
