### ISSUE TITLE
Unfetchable Script.include's lock-up whole script instance 

### ISSUE THREAD

**Issue by humbletim** [highfidelity/hifi#9011]
Test case:
```javascript
print('BEFORE HTTP 404 Not Found...');
Script.include('https://httpbin.org/status/404?' + new Date().getTime().toString(36))
print('//AFTER HTTP 404 Not Found.');
```
When that's loaded [as a Client script](https://raw.githubusercontent.com/humbletim/hifi-aux/master/tests/script-cache/test-client-404.js) it seems to lock up the corresponding script engine forever (ie: never hits the second print). 

Discovered on RELEASE-5622; can confirm that it happens with fresh RELEASE-5648 too.

Per log files the system makes 5 retries to fetch the resource and ultimately prints a final Error message, but never actually seems to return from the fetching process.

The resulting script entry can't be <kbd>(x)</kbd>'d or reloaded from Running Scripts... (the only way to clear it out seems to be restarting Interface).

Same effect can be seen by pasting the above test snippet into the Console... -- the moment Enter is pressed, the prompt seems to locks-up and never returns.

**Comment by humbletim** [comment]
cc #9013

**Comment by sethalves** [comment]
#9013 is merged
