### ISSUE TITLE
clickReleaseOnEntity does not trigger if mouse if moved off instead of released

### ISSUE THREAD

**Issue by Menithal** [highfidelity/hifi#9183]
If a user is interacting with an entity through clickDownOnEntity, but moves mouse off, clickReleaseOnEntity never triggers. 

I suspect  startFarTrigger, stopFarTrigger may behave similarly.

**Comment by ZappoMan** [comment]
Actually, I'm pretty sure that's the intended behavior for the "OnEntity" messages... there are two different "release" messages, one will only trigger if the user releases while still over the entity.

**Comment by Menithal** [comment]
@ZappoMan that may cause some issues in the future, when combined with an a script binding a callback to update thread on interaction start if it is not know about.

This will especially occur to anyone who doesnt know about the above, creates a script that does something on the update thread as an object is being interacted with relying on the release to disconnect the update thread.

So instead of clickDownOnEntity they should use holdingClickOnEntity for sustained events? The issue against this is  the fact that there is no information about how many frames have gone since last callback of the holding event.

This means one is forced to create a timer wrapped in a debounce within holdingClickOnEntity if using the update thread to do something.  To avoid having to do this, could the holdingClickOnEntity event object also contain a delta value?

**Comment by SamGondelman** [comment]
clickReleaseOnEntity was supposed to be called on the entity that you started clicking on, even if you moved off of it.  This was one of the things fixed here: https://github.com/highfidelity/hifi/pull/11584
