### ISSUE TITLE
Segmentation fault caused by audioclient with "pulse" selected as audio output device 

### ISSUE THREAD

**Issue by lboklin** [highfidelity/hifi#9293]
The sound is very hit and miss. After resetting my settings, "alsa_output.*analog-stereo" seems to be the default selected output. While this is selected I don't tend to get any crashes, but the sound works only usually and sometimes not. When this option does not produce any sound I resort to selecting "pulse" or "default" . After selecting "pulse" as output the sound is (usually) working for anything between under a second to a couple of minutes before the segfault happens, from what I can recall of my experience.

This is on KDE Neon (based on Ubuntu 16.04), all packages up to date.

[Terminal debug output gist](https://gist.github.com/lboklin/3a0f9aac4149e37b0c80ec14eddf3018)

**Comment by kencooke** [comment]
@lboklin Thank you for the detailed crash report. It looks related to buffer starvation in your audio backend.  Could you try disabling "output starve detection" to see if that helps? 

This option is in the menu under Developer/Audio/Buffers... check "Disable output starve detection" and increase "Output buffer initial frames" to a larger value, such as 10. Then close and restart Interface.

**Comment by lboklin** [comment]
After spending a minute or two vigorously switching back and forth between the options I have yet to run into a crash, so that seems to have done something and I can see no obvious averse effects to how it runs.
