### ISSUE TITLE
MyAvatar.setBlendshape Resets after a single frame.

### ISSUE THREAD

**Issue by Menithal** [highfidelity/hifi#9356]
I mentioned this a few months back but might as well log it here and in FogBugs to make sure there is visibility

Calling MyAvatar.setBlendshape resets the shapekey nearly within a single frame. This doesnt allow setting avatar Blendshapes if avatar detail customization or emotion systems without face camera tracking (or via just hmd set mood) is every going to be supported or even developed.

Forexample, if I wanted to make my avatar smile (if the avatar would support it): Id use

> MyAvatar.setBlendshape("MouthSmile_R", 1.0);
> MyAvatar.setBlendshape("MouthSmile_L", 1.0);

I'd expect this to stay in place, until the values are set again, such as when talking. However right now it resets the blendshapes to 0.

**Comment by kunalgosar** [comment]
This should be resolved by: https://github.com/highfidelity/hifi/pull/10223
