### ISSUE TITLE
MyAvatar.getAvatarEntityData() Is broken

### ISSUE THREAD

**Issue by WolfGangS** [highfidelity/hifi#9447]
Calling MyAvatar.getAvatarEntityData(), causes a "Critical" error of **unknown Return Type** (see below)

[CRITICAL] [hifi.scriptengine] "[UncaughtException] TypeError: cannot call getAvatarEntityData(): **unknown return type `AvatarEntityMap'** (register the type with qScriptRegisterMetaType()) in Entities 8:32\n[Backtrace]\n    <anonymous>(id = '{a275bceb-f49b-4554-bd9b-f51f30bae780}', ) at **~~~url~~~**:32\n    <global>() at -1"

**Comment by SamGondelman** [comment]
resolved by 9611
