### ISSUE TITLE
"Windows Audio Device Graph Isolation" process eating RAM

### ISSUE THREAD

**Issue by Blair554** [highfidelity/hifi#9469]
I have an issue with the Windows process 'Windows Audio Device Graph Isolation', it will keep consuming RAM as long as Interface is running. This only happens with Interface. 

I have tried: 
Disabled 'Exclusive Mode' and 'Enhancements' in Sound Devices
Disabled on-board Realtek audio in Bios and uninstalled driver
Disabled Oculus integrated audio  
Reinstalled Windows 10

Specs:
Oculus Rift CV1 
Kaby Lake i7-7700K
GA-Z270X-Gaming K5
Kingston HyperX FURY DDR4 2133 (8Gx2) 
Windows 10 Home

**Comment by kencooke** [comment]
Thanks @Blair554. This looks like the Qt code that detects audio device changes is causing a memory/resource leak. I will investigate.

**Comment by kencooke** [comment]
Fixed in PR #9549
