### ISSUE TITLE
Tablet Pop-up relocation: edit > import entities

### ISSUE THREAD

**Issue by cozza13** [highfidelity/hifi#9763]

**Comment by vladest** [comment]
I need icons for all the new Tablet items

**Comment by vladest** [comment]
starting on this

**Comment by vladest** [comment]
PR: https://github.com/highfidelity/hifi/pull/9855

**Comment by ctrlaltdavid** [comment]
Am working on this.

**Comment by ctrlaltdavid** [comment]
PR: https://github.com/highfidelity/hifi/pull/9898

**Comment by ctrlaltdavid** [comment]
Merged into tablet-ui.
