### ISSUE TITLE
Tablet Pop-up relocation:  Developer > Assets > ATP Asset Migration

### ISSUE THREAD

**Issue by cozza13** [highfidelity/hifi#9772]

**Comment by ctrlaltdavid** [comment]
Birarda says no need to port. Could hide menu item in tablet if that's possible to do, or add a note that can only use in desktop window, or remove the menu item totally but keep the code so that it can be re-enabled if needed to be used.

**Comment by ctrlaltdavid** [comment]
Though in theory ATP asset migration should work in the tablet (just need to shorten strings), given that the menu item isn't actually needed it's not really worth the cost of development and testing, so I've disabled the menu item.
PR: https://github.com/highfidelity/hifi/pull/9939

**Comment by ctrlaltdavid** [comment]
The PR hasn't been merged yet so is "still in progress".

**Comment by ctrlaltdavid** [comment]
Merged into master.
