### ISSUE TITLE
Tablet Pop-up relocation: Developer > Network > Disk Cache Editor

### ISSUE THREAD

**Issue by cozza13** [highfidelity/hifi#9776]

**Comment by ctrlaltdavid** [comment]
Asked on #developer and answer is to replace this menu item plus dialog with a menu item, Developer > Network > Clear Disk Cache.

**Comment by ctrlaltdavid** [comment]
PR on master: https://github.com/highfidelity/hifi/pull/9929

**Comment by ctrlaltdavid** [comment]
Merged into master.
