### ISSUE TITLE
Tablet Pop-up relocation: Developer > Network> Show Domain Connection TIming

### ISSUE THREAD

**Issue by cozza13** [highfidelity/hifi#9777]

**Comment by vladest** [comment]
Starting on this

**Comment by ctrlaltdavid** [comment]
This has been merged into tablet-ui.

**Comment by ctrlaltdavid** [comment]
Issue: If Settings > General > HMD Tablet Becomes Toolbar is set and you're in the HMD, the dialog doesn't display in the HMD (it displays the dialog on Interface's desktop window). The desktop version of the dialog should be replaced with a QML one.
