### ISSUE TITLE
Tablet Pop-up relocation: Developer > Log

### ISSUE THREAD

**Issue by cozza13** [highfidelity/hifi#9781]

**Comment by ctrlaltdavid** [comment]
I asked in Slack...
"Developer > Log ... Should this really be ported to the tablet?
If you're trying to use it to debug a tablet function it wouldn't be fruitful to have the log displayed on the tablet (can't display two things at the same time). It might be OK to display the log in an HUD window instead, though desktop display of the dialog while using the HMD might also be preferred sometimes.
I could perhaps add a menu item to select where the dialog is displayed when using the HMD: desktop, HUD, or tablet.
Or perhaps we should just leave Developer > Log displaying only on the desktop, as is."
Need to sort out answer on what esactly's required for this task.
