### ISSUE TITLE
Tablet Pop-up relocation: Developer > Script Log

### ISSUE THREAD

**Issue by cozza13** [highfidelity/hifi#9782]

**Comment by vladest** [comment]
starting on this

**Comment by vladest** [comment]
PR: https://github.com/druiz17/hifi/pull/3

**Comment by vladest** [comment]
PR: https://github.com/highfidelity/hifi/pull/9965

**Comment by vladest** [comment]
Basically, the code was pull requested here https://github.com/druiz17/hifi/pull/3 . but since it was not merged, I recreated PR against highfidelity upstream
