### ISSUE TITLE
Tablet Pop-up relocation: If you click the icon "Snapshot" you will see several popups come up. We will give you the design to change these.

### ISSUE THREAD

**Issue by cozza13** [highfidelity/hifi#9783]

**Comment by cozza13** [comment]
[Tablet_Layouts-Audio-Go-To-Help-Snaps.pdf](https://github.com/highfidelity/hifi/files/852679/Tablet_Layouts-Audio-Go-To-Help-Snaps.pdf)

**Comment by ctrlaltdavid** [comment]
PR: https://github.com/highfidelity/hifi/pull/10029
