### ISSUE TITLE
keyboard doesn't appear when using tree-mode json editor in edit.js

### ISSUE THREAD

**Issue by ctrlaltdavid** [highfidelity/hifi#9890]

**Comment by ctrlaltdavid** [comment]
Tested on tablet-ui branch commit [08ee2fd43f] and it works: keyboard comes up on both tree and code modes when the cursor is in a text field. So, unless I'm missing something, it seems to be working.

**Comment by sethalves** [comment]
if I switch to "tree" mode, and add a new field, the editable text-field that appears doesn't bring a qml keyboard.

**Comment by ctrlaltdavid** [comment]
Still can't repro: keyboard appears with new fields on clean build of latest tablet-ui branch.
