### ISSUE TITLE
If you Stop Default scripts you can not bring up Edit>Running scripts.

### ISSUE THREAD

**Issue by cozza13** [highfidelity/hifi#9916]
Open Tablet. Go to Menu>Edit>Running scripts. Stop all scripts. The tablet will close (this is OK).

Now try and go to Edit>Running scripts from the menu. It will not work.

**Comment by vladest** [comment]
starting on this

**Comment by vladest** [comment]
Please, let me know what is expected behavior in Tablet Mode after stopping all scripts? Edit->Running scripts will not work since its expected to open tablet interface which is stopped now

**Comment by vladest** [comment]
PR: https://github.com/highfidelity/hifi/pull/9954

**Comment by SamGondelman** [comment]
resolved by 9954
