### ISSUE TITLE
Here is the design doc to Change how 'Audio ' looks

### ISSUE THREAD

**Issue by cozza13** [highfidelity/hifi#9947]
[Tablet_Layouts-Audio-Go-To-Help-Snaps (1).pdf](https://github.com/highfidelity/hifi/files/852683/Tablet_Layouts-Audio-Go-To-Help-Snaps.1.pdf)

**Comment by vladest** [comment]
starting on this

**Comment by vladest** [comment]
PR: https://github.com/highfidelity/hifi/pull/10009

**Comment by SamGondelman** [comment]
this was merged a while ago
